# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YGooEpr9iIvWD8s5dHOkObngdQWY2KQe
"""

# app.py
!pip install streamlit yfinance
import streamlit as st
import yfinance as yf
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Fetch data from Yahoo Finance
def fetch_data(ticker):
    data = yf.download(ticker, period="1y")
    data['Tomorrow'] = data['Close'].shift(-1)
    data.dropna(inplace=True)
    return data

# Train the regression model
def train_model(data):
    X = data[['Open', 'High', 'Low', 'Close', 'Volume']]
    y = data['Tomorrow']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

    model = LinearRegression()
    model.fit(X_train, y_train)
    return model, X_test, y_test

# Predict next day's price
def predict_next(model, last_row):
    X_new = last_row[['Open', 'High', 'Low', 'Close', 'Volume']].values.reshape(1, -1)
    return model.predict(X_new)[0]

# Streamlit App UI
st.title("📈 Stock Price Predictor")
ticker = st.text_input("Enter Stock Ticker Symbol", "AAPL")

if st.button("Predict Tomorrow's Price"):
    data = fetch_data(ticker)
    model, X_test, y_test = train_model(data)
    prediction = predict_next(model, data.iloc[-1])
    st.success(f"Predicted Price for Tomorrow: ${prediction:.2f}")
    st.line_chart(data['Close'])